# Generated by Django 5.0 on 2023-12-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate_3_star', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rate_2_star', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rate_1_star', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_pickup', models.ManyToManyField(blank=True, related_name='pickup', to='student_app.student')),
                ('not_pickup', models.ManyToManyField(blank=True, related_name='not_pickup', to='student_app.student')),
            ],
        ),
    ]
