# Generated by Django 5.1.4 on 2025-01-10 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaRatePreset',
            fields=[
                ('preset_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=100, unique=True, verbose_name='Preset name')),
                ('preset_feature_rate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Feature rate')),
                ('preset_r3_rate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='★★★ rate')),
                ('preset_r2_rate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='★★ rate')),
                ('preset_r1_rate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='★ rate')),
            ],
            options={
                'db_table': 'gacha_rate_preset',
            },
        ),
        migrations.CreateModel(
            name='GachaBanner',
            fields=[
                ('banner_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100, unique=True, verbose_name='Banner name')),
                ('banner_image', models.BinaryField(null=True, verbose_name='Banner image')),
                ('banner_non_pickup', models.ManyToManyField(blank=True, related_name='not_pickup', to='student_app.student')),
                ('banner_pickup', models.ManyToManyField(blank=True, related_name='pickup', to='student_app.student')),
                ('preset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha_app.gacharatepreset')),
            ],
            options={
                'db_table': 'gacha_banner',
            },
        ),
        migrations.CreateModel(
            name='GachaTransaction',
            fields=[
                ('transaction_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('banner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha_app.gachabanner')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gacha_transaction',
            },
        ),
    ]
