# Generated by Django 5.1.4 on 2025-01-10 12:58

import django.db.models.deletion
import gacha_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('feature_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('r3_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('r2_rate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('r1_rate', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='GachaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gacha_app.models.banner_image_path)),
                ('is_pickup', models.ManyToManyField(blank=True, related_name='pickup', to='student_app.student')),
                ('not_pickup', models.ManyToManyField(blank=True, related_name='not_pickup', to='student_app.student')),
                ('banner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha_app.gachatype')),
            ],
        ),
        migrations.CreateModel(
            name='GachaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacha_app.gachabanner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
