# Generated by Django 5.0 on 2023-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='student_members', to='gacha_app.student'),
        ),
    ]
