# Generated by Django 5.0 on 2023-12-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_app', '0003_alter_student_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='members',
        ),
    ]
