# Generated by Django 5.0 on 2023-12-12 08:24

import gacha_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_app', '0005_banner_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gacha_app.models.image_upload_path),
        ),
    ]
