# Generated by Django 5.0 on 2023-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacha_app', '0007_gachabannerpreset_delete_banner_school_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='GachaBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate_3_star', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_2_star', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_1_star', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_pickup', models.ManyToManyField(related_name='pickup', to='gacha_app.student')),
                ('not_pickup', models.ManyToManyField(related_name='not_pickup', to='gacha_app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='GachaBannerPreset',
        ),
        migrations.RemoveField(
            model_name='school',
            name='member',
        ),
    ]
